apiVersion: v2
name: y-chart
description: A Helm chart for deploying the Y application.
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: cert-manager
    version: v1.13.3
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled