apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: y-db-pv-claim
  labels:
    app: y-db
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi