apiVersion: v1
kind: Service
metadata:
  name: y-client-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.client.service.port }}
    targetPort: {{ .Values.client.service.port }}
  selector:
    app: {{ .Values.client.appName }}