apiVersion: v1
kind: Service
metadata:
  name: y-db-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.port }}
  selector:
    app: {{ .Values.db.appName }}