apiVersion: apps/v1
kind: Deployment
metadata:
  name: y-db-deployment
  labels:
    app: y-db
spec:
  selector:
    matchLabels:
      app: y-db
  template:
    metadata:
      labels:
        app: y-db
    spec:
      containers:
      - name: y-db-container
        image: mysql:8.2.0
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: y-db-config
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: y-db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: y-db-secret
              key: MYSQL_PASSWORD
        volumeMounts:
          - name: y-db-init
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: y-db-init
          configMap:
            name: y-db-init-config