apiVersion: v1
kind: PersistentVolume
metadata:
  name: y-db-pv
  labels:
    type: local
    app: y-db
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/mysql/y/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: y-db-pv-claim
  labels:
    app: y-db
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi