apiVersion: v1
kind: Service
metadata:
  name: y-db-headless-service
  labels:
    app: y-db
spec:
  ports:
  - port: 3306
    name: web
  clusterIP: None
  selector:
    app: y-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: y-db-stateful
  labels:
    app: y-db
spec:
  serviceName: y-db-headless-service
  replicas: 2
  selector:
    matchLabels:
      app: y-db
  template:
    metadata:
      labels:
        app: y-db
    spec:
      containers:
      - name: y-db-container
        image: mysql:8.2.0
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: y-db-config
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: y-db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: y-db-secret
              key: MYSQL_PASSWORD
        volumeMounts:
          - name: y-db-init
            mountPath: /docker-entrypoint-initdb.d
          - name: y-db-volume
            mountPath: /var/lib/mysql
      volumes:
      - name: y-db-init
        configMap:
          name: y-db-init-config
  volumeClaimTemplates:
  - metadata: 
      name: y-db-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 1Gi
