# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: y-db-pv
#   labels:
#     type: local
#     app: y-db
# spec:
#   storageClassName: microk8s-hostpath
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath: 
#     path: "/opt/mysql/y/data"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: y-db-pv-claim
  labels:
    app: y-db
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi