# Policy to only give the y-api access to the y-db
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: y-network-policy-db
  namespace: y-prod
spec:
  podSelector:
    matchLabels:
      app: y-db
  ingress: []
---
# Policy to isolate the project's namespace, nothing in or out
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: y-network-policy-namespace
  namespace: y-prod
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}