# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: y-product-owner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: y-global-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list", "describe"]
---

# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: y-developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: y-development-all
  namespace: y-dev
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: y-release-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: y-prodction-all
  namespace: y-prod
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]
---

# Account for the y-global-reader role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: y-global-reader-binding
subjects:
- kind: ServiceAccount
  name: y-product-owner
  namespace: default
- kind: ServiceAccount
  name: y-release-manager
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: y-global-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: y-development-all-binding
  namespace: y-dev
subjects:
- kind: ServiceAccount
  name: y-developer
  namespace: y-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: y-development-all
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: y-prodction-all-binding
  namespace: y-prod
subjects:
- kind: ServiceAccount
  name: y-release-manager
  namespace: y-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: y-prodction-all