# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: y-product-owner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: y-global-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list", "describe"]
---
# Account for the y-global-reader role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: y-global-reader-binding
subjects:
- kind: ServiceAccount
  name: y-product-owner
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: y-global-reader