apiVersion: v1
kind: Service
metadata:
  name: y-api-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.port }}
    protocol: TCP
  selector:
    app: {{ .Values.api.appName }}